# Generated by Django 2.2.5 on 2023-02-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrvtime',
            name='nn_kurt',
        ),
        migrations.AddField(
            model_name='hrvtime',
            name='test',
            field=models.FloatField(blank=True, null=True, verbose_name='NN Kurtosis'),
        ),
    ]
