# Generated by Django 2.2.5 on 2023-02-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20230208_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrvtime',
            old_name='test',
            new_name='nn_kurt',
        ),
    ]
