# Generated by Django 2.2.5 on 2023-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20230208_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='name_study',
            field=models.CharField(max_length=200, verbose_name='Study Name'),
        ),
    ]
