# Generated by Django 2.2.5 on 2023-02-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20230210_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
    ]
