# Generated by Django 2.2.5 on 2023-03-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20230218_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='patient_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='patient_conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='patient_exams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='hrvfreq',
            name='collectdata_freq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.CollectData', verbose_name='Collect Data ID'),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='collectdata_non_lin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.CollectData', verbose_name='Collect Data ID'),
        ),
        migrations.AlterField(
            model_name='hrvtime',
            name='collectdata_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.CollectData', verbose_name='Collect Data ID'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient_medicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient ID'),
        ),
    ]
