# Generated by Django 3.1.2 on 2022-10-27 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20221027_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.CharField(max_length=50)),
                ('study', models.PositiveSmallIntegerField(choices=[(1, 'DOC_SC'), (2, 'Extra_data_Prof_jan22')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('ecg', models.BooleanField(default=False)),
                ('ppg', models.BooleanField(default=False)),
                ('abp', models.BooleanField(default=False)),
                ('abspathrecord_times', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('sampling_freq_hz', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('device', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('ecg_processing_status', models.BooleanField(default=False)),
                ('ppg_processing_status', models.BooleanField(default=False)),
                ('brs_processing_status', models.BooleanField(default=False)),
                ('observations', models.TextField(max_length=1000)),
                ('patient_exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
