# Generated by Django 2.2.5 on 2023-03-06 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20230306_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='collected_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Collected Data'),
        ),
    ]
