# Generated by Django 3.1.2 on 2022-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20221027_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='atividade_fisica',
            new_name='physical_activity',
        ),
    ]
