# Generated by Django 3.1.2 on 2022-11-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20221125_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='patient_medicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
