# Generated by Django 3.1.2 on 2022-12-13 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20221130_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRVTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('nn_mean', models.FloatField(null=True)),
                ('nn_median', models.FloatField(null=True)),
                ('nn_mode', models.FloatField(null=True)),
                ('nn_variance', models.FloatField(null=True)),
                ('nn_skew', models.FloatField(null=True)),
                ('nn_kurt', models.FloatField(null=True)),
                ('nn_iqr', models.FloatField(null=True)),
                ('sd_nn', models.FloatField(null=True)),
                ('cv', models.FloatField(null=True)),
                ('rmssd', models.FloatField(null=True)),
                ('sdsd', models.FloatField(null=True)),
                ('nn50', models.FloatField(null=True)),
                ('pnn50_pr', models.FloatField(null=True)),
                ('nn20', models.FloatField(null=True)),
                ('pnn20', models.FloatField(null=True)),
                ('pnn20_pr', models.FloatField(null=True)),
                ('hr_change', models.FloatField(null=True)),
                ('gti', models.FloatField(null=True)),
                ('tinn', models.FloatField(null=True)),
                ('si', models.FloatField(null=True)),
                ('collectdata_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.collectdata')),
            ],
        ),
        migrations.CreateModel(
            name='HRVFreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('ulf_lomb_ms2', models.FloatField(null=True)),
                ('vlf_lomb_ms2', models.FloatField(null=True)),
                ('lf_lomb_ms2', models.FloatField(null=True)),
                ('hf_lomb_ms2', models.FloatField(null=True)),
                ('ulf_lomb_log', models.FloatField(null=True)),
                ('vlf_lomb_log', models.FloatField(null=True)),
                ('lf_lomb_log', models.FloatField(null=True)),
                ('hf_lomb_log', models.FloatField(null=True)),
                ('ttlpwr_lomb_ms2', models.FloatField(null=True)),
                ('lf_hf_lomb', models.FloatField(null=True)),
                ('power_vlf_lomb', models.FloatField(null=True)),
                ('power_lf_lomb', models.FloatField(null=True)),
                ('power_hf_lomb', models.FloatField(null=True)),
                ('lf_nu_lomb', models.FloatField(null=True)),
                ('hf_nu_lomb', models.FloatField(null=True)),
                ('ulf_welch', models.FloatField(null=True)),
                ('vlf_welch', models.FloatField(null=True)),
                ('lf_welch', models.FloatField(null=True)),
                ('hf_welch', models.FloatField(null=True)),
                ('ttlpwr_welch', models.FloatField(null=True)),
                ('lfhf_welch', models.FloatField(null=True)),
                ('power_vlf_welch', models.FloatField(null=True)),
                ('power_lf_welch', models.FloatField(null=True)),
                ('power_hf_welch', models.FloatField(null=True)),
                ('lf_nu_welch', models.FloatField(null=True)),
                ('hf_nu_welch', models.FloatField(null=True)),
                ('collectdata_freq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.collectdata')),
            ],
        ),
    ]
