# Generated by Django 3.1.2 on 2022-12-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_hrvfreq_hrvtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrvfreq',
            name='collectdata_freq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.collectdata'),
        ),
        migrations.AlterField(
            model_name='hrvtime',
            name='collectdata_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.collectdata'),
        ),
    ]
