# Generated by Django 2.2.5 on 2023-01-13 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20230109_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conditions',
            new_name='Condition',
        ),
        migrations.RenameModel(
            old_name='ExamsResults',
            new_name='ExamsResult',
        ),
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
