# Generated by Django 2.2.5 on 2023-01-24 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_auto_20230124_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sbp_repous',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
