# Generated by Django 2.2.5 on 2023-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0029_auto_20230124_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='alpha1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='alpha2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='area_sodp_rr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='area_sodp_rr_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='csi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ctm_r1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ctm_r2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ctm_r3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='cvi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='d2_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='d2_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ellipse_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_amostra_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_amostra_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_1_01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_1_015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_1_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_1_025',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_2_01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_2_015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_2_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_aprox_2_025',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_conditional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_corrected_cond',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_fuzzy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_multiescala_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_multiescala_e5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_permutation_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_permutation_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_shannon_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_shannon_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='ent_spectral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='mean_dr1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='mean_dr2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='mean_dr3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='mean_dr4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='mean_dr5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='norm_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='sd1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='sd1_sd2_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrvnonlinear',
            name='sd2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
