# Generated by Django 2.2.5 on 2023-01-24 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_auto_20230124_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='abp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='abspathrecord_times',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='device',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='ecg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='emg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='ppg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='sampling_freq_hz',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
