# Generated by Django 2.2.5 on 2023-01-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_auto_20230124_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='file_hrv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='observations',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
