# Generated by Django 2.2.5 on 2023-01-25 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0038_auto_20230125_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsresult',
            name='acr_alb_creat',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Acr Alb_Creat'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='basek',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Basek'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='clear_creatinina',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Clear Creatinina'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collected Data'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='creatina_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Creatina Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='creatina_umol_l',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Creatina Umol_L'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ct_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ct Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ct_mmol_l',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ct Mmol_L'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='glicemia_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Glicemia Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='glicemia_mmol_l',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Glicemia Mmol_L'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hb_g_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hb G_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hba1c_mmol_mol',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hba1C Mmol_Mol'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hba1c_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hba1C Percent'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hdl_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hdl Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ldl_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ldl Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='microAlb',
            field=models.BooleanField(default=False, verbose_name='Microalb'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='na',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Na'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='patient_exams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient Exams'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='rpc_prot_creat',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Rpc Prot_Creat'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tg_mg_dl',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Tg Mg_Dl'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tg_mmol_l',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Tg Mmol_L'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tsh',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Tsh'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ureia',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ureia'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='urine_albumina_mg_24h',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Urine Albumina_Mg_24H'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitb12',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vitb12'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitd',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vitd'),
        ),
    ]
