# Generated by Django 2.2.5 on 2023-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0041_auto_20230125_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='ecg_signal',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ecg Signal'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='observations',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observations'),
        ),
    ]
