# Generated by Django 2.2.5 on 2023-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0042_auto_20230125_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrvtime',
            name='pnn20',
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='ecg_signal',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ecg Signal (.txt)'),
        ),
    ]
