# Generated by Django 2.2.5 on 2023-01-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0043_auto_20230125_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrvtime',
            old_name='gti',
            new_name='hti',
        ),
    ]
