# Generated by Django 2.2.5 on 2023-02-03 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0051_auto_20230203_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='abp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ABP'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='abspathrecord_times',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Abspathrecord Times'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='device',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='ecg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ECG'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='emg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='EMG'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='ppg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='PPG'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='sampling_freq_hz',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sampling (Freq_Hz)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='pn_signs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PN Signs'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='pn_symptoms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PN Symptoms'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='acr_alb_creat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='ACR Alb_Creat'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='basek',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Baseline Potássio'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='clear_creatinina',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Clear Creatinina'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='creatina_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Creatina (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='creatina_umol_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Creatina (Umol_L)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ct_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Colesterol Total (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ct_mmol_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Colesterol Total (Mmol_L)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='glicemia_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Glicemia (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='glicemia_mmol_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Glicemia (Mmol_L)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hb_g_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hb g_dL'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hba1c_mmol_mol',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='HbA1c (Mmol_Mol)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hba1c_percent',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='HbA1c (%)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='hdl_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='HDL (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ldl_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='LDL (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='na',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sódio'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='rpc_prot_creat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='RPC Prot_Creat'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tg_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Triglicerídeos (Mg_dL)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tg_mmol_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Triglicerídeos (Mmol_L)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='tsh',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hormônio Tireoestimulante'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='ureia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ureia'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='urine_albumina_mg_24h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Urine Albumina (Mg_24H)'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitb12',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vit B12'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vit D'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='aas_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='AAS (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='atorvas_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Atorvas (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='carbamazpn_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Carbamazpn (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='enalapril_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Enalapril (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='losartan_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Losartan (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='lt4_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='LT4 (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mtf_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='MTF (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='omeprazol_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Omeprazol (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quetiapina_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Quetiapina (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ranitidina_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ranitidina (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='rosuvas_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Rosuvas (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sinvas_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sinvas (Mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='venlafaxina_mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Venlafaxina (Mg)'),
        ),
    ]
