# Generated by Django 2.2.5 on 2023-02-07 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0053_auto_20230203_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='(DDD) 9 9999-9999', max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_dm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Does Not Have'), (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3 Gestational')], default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Type DM'),
        ),
    ]
