# Generated by Django 3.1.2 on 2022-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_collectdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectdata',
            old_name='patient_exams',
            new_name='patient_data',
        ),
    ]
