# Generated by Django 3.1.2 on 2022-10-27 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examsresults',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicines',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
