# Generated by Django 3.1.2 on 2022-10-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20221027_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collected_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
