# Generated by Django 3.1.2 on 2022-10-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20221027_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='patient',
            new_name='patient_conditions',
        ),
        migrations.RenameField(
            model_name='medicines',
            old_name='patient',
            new_name='patient_medicines',
        ),
    ]
