# Generated by Django 3.1.2 on 2022-11-25 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20221124_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
