# Generated by Django 2.2.5 on 2023-01-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_auto_20221214_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrvtime',
            name='file_hrvtime',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
