# Generated by Django 2.2.5 on 2023-01-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20230103_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='brs_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='observations',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
