# Generated by Django 2.2.5 on 2023-01-20 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_auto_20230114_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectdata',
            name='brs_processing_status',
        ),
        migrations.RemoveField(
            model_name='collectdata',
            name='ecg_processing_status',
        ),
        migrations.RemoveField(
            model_name='collectdata',
            name='ppg_processing_status',
        ),
        migrations.AddField(
            model_name='collectdata',
            name='emg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='study',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DOC_SC'), (2, 'Extra_data_Prof_jan22')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
