# Generated by Django 2.2.5 on 2023-01-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_auto_20230120_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrvfreq',
            name='file_hrvfreq',
        ),
        migrations.RemoveField(
            model_name='hrvtime',
            name='file_hrvtime',
        ),
    ]
