# Generated by Django 2.2.5 on 2023-01-20 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_auto_20230120_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRVNonLinear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sd1', models.FloatField(null=True)),
                ('sd2', models.FloatField(null=True)),
                ('sd1_sd2_ratio', models.FloatField(null=True)),
                ('ellipse_area', models.FloatField(null=True)),
                ('csi', models.FloatField(null=True)),
                ('cvi', models.FloatField(null=True)),
                ('alpha1', models.FloatField(null=True)),
                ('alpha2', models.FloatField(null=True)),
                ('d2_10', models.FloatField(null=True)),
                ('d2_20', models.FloatField(null=True)),
                ('ent_aprox_1_01', models.FloatField(null=True)),
                ('ent_aprox_1_015', models.FloatField(null=True)),
                ('ent_aprox_1_02', models.FloatField(null=True)),
                ('ent_aprox_1_025', models.FloatField(null=True)),
                ('ent_aprox_2_01', models.FloatField(null=True)),
                ('ent_aprox_2_015', models.FloatField(null=True)),
                ('ent_aprox_2_02', models.FloatField(null=True)),
                ('ent_aprox_2_025', models.FloatField(null=True)),
                ('ent_amostra_1', models.FloatField(null=True)),
                ('ent_amostra_2', models.FloatField(null=True)),
                ('ent_multiescala_e3', models.FloatField(null=True)),
                ('ent_multiescala_e5', models.FloatField(null=True)),
                ('ent_fuzzy', models.FloatField(null=True)),
                ('ent_shannon_1', models.FloatField(null=True)),
                ('ent_shannon_2', models.FloatField(null=True)),
                ('ent_spectral', models.FloatField(null=True)),
                ('ent_permutation_1', models.FloatField(null=True)),
                ('norm_entropy', models.FloatField(null=True)),
                ('ent_permutation_2', models.FloatField(null=True)),
                ('ent_conditional', models.FloatField(null=True)),
                ('ent_corrected_cond', models.FloatField(null=True)),
                ('ctm_r1', models.FloatField(null=True)),
                ('ctm_r2', models.FloatField(null=True)),
                ('ctm_r3', models.FloatField(null=True)),
                ('area_sodp_rr_log', models.FloatField(null=True)),
                ('area_sodp_rr', models.FloatField(null=True)),
                ('mean_dr1', models.FloatField(null=True)),
                ('mean_dr2', models.FloatField(null=True)),
                ('mean_dr3', models.FloatField(null=True)),
                ('mean_dr4', models.FloatField(null=True)),
                ('mean_dr5', models.FloatField(null=True)),
                ('collectdata_non_lin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.CollectData')),
            ],
        ),
    ]
