# Generated by Django 2.2.5 on 2023-01-25 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0034_auto_20230125_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collected_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
