# Generated by Django 2.2.5 on 2023-01-25 20:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0036_auto_20230125_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_dm_diagnosis',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Age Dm_Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alcohol',
            field=models.BooleanField(default=False, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(450.0)], verbose_name='Bmi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brs_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brs Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bsa',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)], verbose_name='Bsa'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='can_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Can Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collected Data'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_change',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Dbp Change'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_empe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Dbp Empe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_repous',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Dbp Repous'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dm',
            field=models.BooleanField(default=False, verbose_name='Dm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dm_duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Dm Duration'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hipo_mes',
            field=models.SmallIntegerField(default=0, verbose_name='Hipo Mes'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='initials',
            field=models.CharField(max_length=10, verbose_name='Initials'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='internacao_dm',
            field=models.BooleanField(default=False, verbose_name='Internacao Dm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mean_hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Mean Hr'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='obrienc_cs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Obrienc Cs'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='observations',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physical_activity',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Physical Activity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postural_drop',
            field=models.BooleanField(blank=True, null=True, verbose_name='Postural Drop'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_db',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rr Db'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_resting',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rr Resting'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_standing',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rr Standing'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_valsalva',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rr Valsalva'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_change',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sbp Change'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_empe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sbp Empe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_repous',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sbp Repous'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoker',
            field=models.BooleanField(default=False, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subject_name',
            field=models.CharField(max_length=200, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_dm',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Type Dm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='Weight'),
        ),
    ]
