# Generated by Django 2.2.5 on 2023-01-25 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0037_auto_20230125_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='observations',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ace_arb',
            field=models.BooleanField(default=False, verbose_name='Ace Arb'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='anticoncepcional',
            field=models.BooleanField(default=False, verbose_name='Anticoncepcional'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ass_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ass Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='atorvas_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Atorvas Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='carbamazpn_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Carbamazpn Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collected Data'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='enalapril_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Enalapril Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='insulin',
            field=models.BooleanField(default=False, verbose_name='Insulin'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='losartan_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Losartan Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='lt4_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Lt4 Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mtf_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Mtf Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='omeprazol_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Omeprazol Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient_medicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient Medicines'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quetiapina_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Quetiapina Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ranitidina_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ranitidina Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='rosuvas_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Rosuvas Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sinvas_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sinvas Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='venlafaxina_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Venlafaxina Mg'),
        ),
    ]
