# Generated by Django 2.2.5 on 2023-01-25 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0039_auto_20230125_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='ace_arb',
            field=models.BooleanField(default=False, verbose_name='Ace Arb'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='collected_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collected Data'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='doenca_celiaca',
            field=models.BooleanField(default=False, verbose_name='Doenca Celiaca'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='doenca_pulmonar',
            field=models.BooleanField(default=False, verbose_name='Doenca Pulmonar'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='drge',
            field=models.BooleanField(default=False, verbose_name='Drge'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='nephropathy',
            field=models.BooleanField(default=False, verbose_name='Nephropathy'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='patient_conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Patient Conditions'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='peripheral_neuropathy',
            field=models.BooleanField(default=False, verbose_name='Peripheral Neuropathy'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='pn_signs',
            field=models.CharField(max_length=200, verbose_name='Pn Signs'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='pn_symptoms',
            field=models.CharField(max_length=200, verbose_name='Pn Symptoms'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='retinopathy',
            field=models.BooleanField(default=False, verbose_name='Retinopathy'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='tireoide',
            field=models.BooleanField(default=False, verbose_name='Tireoide'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='vitiligo',
            field=models.BooleanField(default=False, verbose_name='Vitiligo'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='microAlb',
            field=models.BooleanField(default=False, verbose_name='Micro Alb'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitb12',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vit B12'),
        ),
        migrations.AlterField(
            model_name='examsresult',
            name='vitd',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Vit D'),
        ),
    ]
