# Generated by Django 2.2.5 on 2023-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0046_auto_20230126_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='ecg_signal',
            field=models.FileField(blank=True, null=True, upload_to='txt/', verbose_name='Ecg Signal (.txt)'),
        ),
    ]
