# Generated by Django 2.2.5 on 2023-02-03 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0048_auto_20230201_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='ass_mg',
        ),
        migrations.AddField(
            model_name='medicine',
            name='aas_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='AAS Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='lt4_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='LT4 Mg'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mtf_mg',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='MTF Mg'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_dm_diagnosis',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Age DM Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(450.0)], verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bsa',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)], verbose_name='BSA'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_change',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='DBP Change'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_empe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='DBP Empe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dbp_repous',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='DBP Repous'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dm',
            field=models.BooleanField(default=False, verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dm_duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='DM Duration'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(help_text='EX: 1,82', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Height (m)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='internacao_dm',
            field=models.BooleanField(default=False, verbose_name='Internation DM'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='obrienc_cs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Obrienc CS'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_db',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='RR Deep Breathing'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_resting',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='RR Resting'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_standing',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='RR Standing'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rr_valsalva',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='RR Valsalva'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_change',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='SDP Change'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_empe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='SDP Empe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sbp_repous',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='SDP Repous'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_dm',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Type DM'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(help_text='EX: 65,5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='Weight (kg)'),
        ),
    ]
