# Generated by Django 2.2.5 on 2023-02-08 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0054_auto_20230207_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type_dm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Does Not Have'), (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3 Gestational')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Type DM'),
        ),
    ]
