# Generated by Django 2.2.5 on 2023-02-08 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0055_auto_20230208_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collected Data')),
                ('name_study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Name')),
            ],
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Study', verbose_name='Study'),
        ),
    ]
